[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com

dns-server = 223.5.5.5,119.29.29.29,https://1.1.1.1/dns-query

ipv6 = false

update-url = https://cdn.jsdelivr.net/gh/xunchang20808/shadowrocket-rules@main/rules.conf


[Rule]

# 广告拦截
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Advertising.list,REJECT

# 银行
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Bank.list,DIRECT

# Apple
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Apple.list,DIRECT

# 微信
DOMAIN-SUFFIX,wechat.com,DIRECT
DOMAIN-SUFFIX,weixin.qq.com,DIRECT
DOMAIN-SUFFIX,qq.com,DIRECT
PROCESS-NAME,WeChat,DIRECT

# AI
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/AI.list,TOKYO

# Google
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Google.list,TOKYO

# Telegram
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Telegram.list,TOKYO

# TikTok
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/TikTok.list,SEATTLE

# 流媒体
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Streaming.list,SEATTLE

# 中国流量
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/China.list,DIRECT

# 最终规则
FINAL,SEATTLE