[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
dns-server = system,223.5.5.5,119.29.29.29,1.1.1.1
ipv6 = false

[Rule]

# 广告拦截
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Advertising.list,REJECT

# 银行直连
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Bank.list,DIRECT

# Apple服务
DOMAIN-SUFFIX,apple.com,DIRECT
DOMAIN-SUFFIX,icloud.com,DIRECT
DOMAIN-SUFFIX,mzstatic.com,DIRECT

# AI
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/ai.list,SEATTLE

# TikTok
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/tiktok.list,SEATTLE

# Google
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/google.list,TOKYO

# Telegram
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/telegram.list,TOKYO

# Streaming
RULE-SET,https://raw.githubusercontent.com/xunchang20808/shadowrocket-rules/main/RULE-SET/Streaming.list,SEATTLE

# 中国IP
GEOIP,CN,DIRECT

# 默认
MATCH,TOKYO